version: '2'

services:
  testshell:
    image: mcr.microsoft.com/vscode/devcontainers/base:0-alpine-${VARIANT:?Cannot find env VARIANT}
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached